### ISSUE TITLE
Local dev section needs some context

### ISSUE THREAD

**Issue by ainsleys** [lauraweindorf/enigma-dev-x#6]
Can you add some context for this section? It's not clear how this / links to name-app relate to the earlier part of the guide

https://github.com/lauraweindorf/enigma-dev-x#local-dev-with-docker-and-cosmwasm-cli

**Comment by lauracw100** [comment]
I agree. I'll try to add some context. cc @levackt if you have any notes on this, let me know?

**Comment by ainsleys** [comment]
Thanks Laura! I think we can even explain at the beginning at a high-level what is supposed to happen in each section... I.e., 

- "the first part of this guide will set up a local enigma blockchain developer environment"... 
- "the second part will set up cosmwasm developer environment, including faucet and (xyz anything else)" 
- "The third part will walk you thru a specific example called "name-app" that will show you how to do (xyz different things)". 

Does that list look right to you both?

**Comment by lauracw100** [comment]
Yes, that looks right to me,

**Comment by levackt** [comment]
Yes it's a leap from the counter, new sections can clarify what new things
came in the kitchen sink, and these can also be different guides.
The counter could use a section generating a react front end and connect
the wallet with mnemonic from the docker build.
No faucet needed since the docker container mints on startup anyway.

It could also use a conversion or side by side comparison of using JS to do
the deployment etc

**Comment by ainsleys** [comment]
Great, much improved.
